// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Factor")
                        .HasColumnType("float");

                    b.Property<string>("OccupationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Occupations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Factor = 1.5,
                            OccupationName = "Cleaner",
                            Rating = "Light Manual"
                        },
                        new
                        {
                            Id = 2,
                            Factor = 1.0,
                            OccupationName = "Doctor",
                            Rating = "Professional"
                        },
                        new
                        {
                            Id = 3,
                            Factor = 1.25,
                            OccupationName = "Author",
                            Rating = "White Collar"
                        },
                        new
                        {
                            Id = 4,
                            Factor = 1.75,
                            OccupationName = "Farmer",
                            Rating = "Heavy Manual"
                        },
                        new
                        {
                            Id = 5,
                            Factor = 1.75,
                            OccupationName = "Mechanic",
                            Rating = "Heavy Manual"
                        },
                        new
                        {
                            Id = 6,
                            Factor = 1.5,
                            OccupationName = "Florist",
                            Rating = "Light Manual"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
